# Generated by Django 5.0.6 on 2024-06-20 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('sub_monto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_general', models.DecimalField(decimal_places=2, max_digits=20)),
                ('presente', models.BooleanField(null=True)),
                ('iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.opciones', to_field='valor_iva')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedor', to_field='cedula')),
            ],
        ),
    ]
